### ISSUE TITLE
Font detection

### ISSUE THREAD

**Issue by greenlikeorange** [setkyar/URWeather#2]
Check out https://github.com/greenlikeorange/URWeather/tree/font-detector
I added https://github.com/myatmins/MDetect to project and add `isUnicode` field on state

**Comment by setkyar** [comment]
Thanks, bro. I will close the issue when I commit to your changes. Thanks.

**Comment by setkyar** [comment]
Added now, bro. Here is the [commit](https://github.com/setkyar/URWeather/commit/db1234c50e49d815d265a45a1c9d097c0ccda8b0).
